routes/web.php
        Route::get('/{slug}', 'Master\Media\VideoController@show')->name('media.video.show');
    });

    Route::group(['prefix' => 'sermons'], function () {
        Route::get('/', 'Master\Media\SermonController@index')->name('media.sermons');
        Route::get('/pastor/{name}', 'Master\Media\SermonCategoriesController@pastor')->name('media.sermons.pastor');
        Route::get('/pastor/{name}/{sermon_slug}', 'Master\Media\SermonCategoriesController@pastor_sermon')->name('media.sermons.pastor.show');
        Route::get('/search', 'Master\Media\SermonController@search')->name('media.sermon.search');
        Route::get('/{slug}', 'Master\Media\SermonController@show')->name('media.sermon.show');
    });
});

Route::group(['prefix' => 'about'], function () {
    Route::get('/', 'Master\AboutController@index')->name('about');
    Route::get('/church', 'Master\AboutController@church')->name('about.church');
    Route::get('/staff', 'Master\AboutController@staff')->name('about.staff');
    Route::get('/staff/{slug}', 'Master\AboutController@show')->name('about.staff.show');
    Route::get('/leaders', 'Master\AboutController@leaders')->name('about.leaders');
    Route::get('/leaders/{slug}', 'Master\AboutController@show')->name('about.leaders.show');
    Route::get('/bylaws', 'Master\AboutController@doc')->name('about.bylaws');
    Route::get('/contact-us', 'Master\ContactUsController@index')->name('about.contact');

    Route::group(['prefix' => 'committees'], function () {
        Route::get('/', 'Master\Committees\IndexController@index')->name('about.committees');
        Route::get('/{slug}', 'Master\Committees\IndexController@show')->name('about.committees.show');
    });
});

// Old Routes
Route::group(['prefix' => 'current'], function () {
    Route::get('/news', function () { return redirect(route('happenings.news_events')); });
    Route::get('/events', function () { return redirect(route('happenings.news_events')); });
    Route::get('/calendar', function () { return redirect(route('happenings.calendar')); });
});

Route::group(['prefix' => 'happenings'], function () {
    Route::get('/', 'Master\Happenings\IndexController@index')->name('happenings');
    //NEWS
    Route::get('news', 'Master\Happenings\NewsController@index')->name('happenings.news.index');
    Route::get('news/{slug}', 'Master\Happenings\NewsController@show')->name('happenings.news.show');
    //EVENTS
    Route::get('events', 'Master\Happenings\EventsController@index')->name('happenings.events.index');
    Route::get('events/{slug}', 'Master\Happenings\EventsController@show')->name('happenings.event.show');
    //CALENDAR
    Route::get('calendar', 'Master\Happenings\IndexController@calendar')->name('happenings.calendar');
});

// Old Routes
Route::group(['prefix' => 'ministry'], function () {
    Route::get('/missions', function () { return redirect(route('ministries.missions')); });
    Route::get('/mans', function () { return redirect(route('ministries.mens')); });
    Route::get('/womans', function () { return redirect(route('ministries.womens')); });
    Route::get('/care', function () { return redirect(route('ministries.care')); });
});

Route::group(['prefix' => 'ministries'], function () {
    Route::get('/', 'Master\Ministries\IndexController@index')->name('ministries');
    Route::get('/missions/member/{slug}', 'Master\Ministries\MissionsController@member')->name('ministries.missions.member');
    Route::get('/missions/{slug}', 'Master\Ministries\MissionsController@ministry')->name('ministries.missions.ministry');
    Route::get('/missions', 'Master\Ministries\MissionsController@index')->name('ministries.missions');
    Route::get('/mens', 'Master\Ministries\MensController@index')->name('ministries.mens');
    Route::get('/women', 'Master\Ministries\WomensController@index')->name('ministries.womens');
    Route::get('/women/{slug}', 'Master\Ministries\WomensController@show')->name('ministries.womens.show');
    Route::get('/care/{slug}', 'Master\Ministries\CareController@ministry')->name('ministries.care.ministry');
    Route::get('/care', 'Master\Ministries\CareController@index')->name('ministries.care');
});
Route::get('/give', 'Master\GiveController@index')->name('give');
Route::get('/photoalbums/{slug}', 'Master\PhotoalbumsController@show')->name('photoalbums.show');
Route::get('/photoalbums', 'Master\PhotoalbumsController@index')->name('photoalbums');


Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/directory', 'Master\Directory\IndexController@index')->name('directory');
    Route::get('/directory/member/{id}', 'Master\Directory\IndexController@show')->name('directory.member');

    Route::get('profile', 'Master\User\IndexController@index')->name('profile');
});

//Admin routes----------------------------------------------------------------------------------------------------------
Route::group(['prefix' => 'admin'], function(){

    Route::get('check', function(){
        return new App\Mail\AdministratorPasswordChanged(App\Admin::find(1), '123456');
    });

    Route::group(['middleware' => ['guest:admin']], function () {
        Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'Admin\Auth\LoginController@login')->name('admin.login.submit');
        //Reset Admin Password
        Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.password.update');
        Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
    });

    Route::group(['middleware' => ['auth:admin', 'pchecker']], function () {
        Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');
        Route::get('/', 'Admin\Dashboard\IndexController@index')->name('admin.dashboard');
        Route::get('/dashboard', function () { return redirect('/admin');});

        //Search for member
        Route::post('/search/member/', 'Admin\SearchController@getMember');
        //Documents
        Route::resource('/documents', 'Admin\Docs\IndexController');
        //Committees
        Route::resource('/committees', 'Admin\Committees\IndexController');
        Route::resource('/committees/member', 'Admin\Committees\MembersController');
        //Ministries
        Route::resource('/ministries', 'Admin\Ministries\IndexController');
        Route::resource('/ministries/member', 'Admin\Ministries\MembersController', ['except' =>['index', 'show']]);
        Route::resource('/ministries/liaison', 'Admin\Ministries\LiaisonsController', ['except' =>['index', 'show']]);
        //Empowerment
        Route::resource('groups/{id}/member', 'Admin\Empowerment\MembersController', ['except' =>['index', 'show', 'edit']]);
        Route::resource('groups', 'Admin\Empowerment\GroupsController');

        //Videos
        Route::resource('/videos', 'Admin\Video\IndexController');
        //Events
        Route::group(['prefix' => 'events'], function () {
            Route::resource('/meta/location', 'Admin\Events\LocationController', ['except' => ['index', 'show']]);
            Route::resource('/meta', 'Admin\Events\MetaController', ['except' => ['show']]);
            Route::resource('/members', 'Admin\Events\MembersController', ['only' => ['create', 'store', 'destroy']]);
            Route::resource('/price', 'Admin\Events\PriceController', ['except' => ['index', 'show']]);
            Route::resource('/picture', 'Admin\Events\PictureController', ['only' =>['create', 'store', 'destroy']]);
        });
        Route::resource('/events', 'Admin\Events\IndexController');
        //News
        Route::resource('/news/picture', 'Admin\News\PictureController', ['only' =>['create', 'store', 'destroy']]);
        Route::resource('/news', 'Admin\News\IndexController');
        //Sermons
        Route::resource('/sermons', 'Admin\Sermons\IndexController');
        Route::group(['prefix' => 'sermons'], function () {
            Route::post('/search/related', 'Admin\Sermons\SearchController@related');
            Route::resource('/file', 'Admin\Sermons\FileController');
            Route::resource('/relation', 'Admin\Sermons\RelationController', ['only' =>['edit', 'update', 'destroy']]);
        });
        //Photoalbum
        Route::resource('/photoalbums', 'Admin\Photoalbum\IndexController');
        Route::group(['prefix' => 'photoalbums'], function () {
            Route::resource('/pictures', 'Admin\Photoalbum\PictureController');
        });
        //Picture
        //Route::resource('/pictures', 'Admin\Pictures\IndexController');
        //Route::group(['prefix' => 'pictures'], function () {
            //Route::post('/search/related', 'Admin\Sermons\SearchController@related');
        //});

        //Accounts
        Route::group(['prefix' => 'accounts'], function () {

            Route::get('/', function () { return redirect('/admin/accounts/users');});

            Route::resource('/admins/password', 'Admin\Accounts\AdminsPasswordController', ['only' =>['edit', 'update']]);
            Route::resource('/admins', 'Admin\Accounts\AdminsController');

            Route::match(['get', 'post'], '/users/{id}/verify', 'Admin\Accounts\UserController@verifyUser');
            Route::post('/users/{id}/reset-password', 'Admin\Accounts\IndexController@resetPassword');

            Route::resource('/users', 'Admin\Accounts\UserController');
            Route::group(['prefix' => 'users'], function () {
                Route::resource('/picture', 'Admin\Accounts\UserPictureController');
                Route::resource('/address', 'Admin\Accounts\AddressController');

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    protected $fillable = [
        'first_name', 'last_name', 'middle_name', 'slug', 'user_id', 'dob', 'picture_id', 'deleted_at'
    ];

    //DB Relationships -------------------------------------------------------------------------------------------------
    public function userAccount()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function profilePicture()
    {
        return $this->belongsTo('App\Picture', 'picture_id');
    }

    public function phones()
    {
        return $this->hasMany('App\Phone', 'member_id');
    }

    public function titles()
    {
        return $this->belongsToMany('App\Title', 'member_titles', 'member_id')->withPivot('id', 'term_started', 'term_ended');
    }

    public function story()
    {
        return $this->belongsTo('App\MemberStory', 'id', 'member_id');
    }

    public function emails()
    {
        return $this->hasMany('App\Email', 'member_id');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role', 'user_roles', 'member_id', 'role_id');
    }

    public function videos()
    {
        return $this->belongsToMany('App\Video', 'member_videos', 'member_id', 'video_id');
    }

    public function sermons()
    {
        return $this->belongsToMany('App\Sermon', 'member_sermons', 'member_id', 'sermon_id');
    }

    //Missions Supported Ministries
    public function ministries()
    {
        return $this->belongsToMany('App\Ministry', 'ministry_liaisons')->withPivot('id', 'term_started', 'term_ended');
    }

    // Mutators --------------------------------------------------------------------------------------------------------
    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = strtolower($value);
    }

    public function setFirstNameAttribute($value)
    {
        $this->attributes['first_name'] = ucfirst(strtolower($value));
    }

    public function setLastNameAttribute($value)
    {
        $this->attributes['last_name'] = ucfirst(strtolower($value));
    }

    public function setMiddleNameAttribute($value)
    {
        $this->attributes['middle_name'] = ucfirst(strtolower($value));
    }

    public function setDobAttribute($value)
    {
        $this->attributes['dob'] = date('Y-m-d', strtotime($value));
    }

    // Accessors -------------------------------------------------------------------------------------------------------
    public function getDobAttribute($value)
    {
        if($value)
            return date('m/d/Y', strtotime($value));
        else
            return null;
    }

    public function getBirthDateAttribute()
    {
        if($this->dob)
            return date('m/d/Y', strtotime($this->dob));
        else
            return "<em>- not specified -</em>";
    }

    public function getFullNameAttribute()
    {
        if($this->middle_name)
            return "$this->first_name $this->middle_name $this->last_name";
        else
            return "$this->first_name $this->last_name";
    }

    public function getTitlesListAttribute()
    {
        $result = null;
        foreach($this->titles as $title){
            if($title->parent_id)
                $result .= $title->parent->title. ' &bullet; '. $title->title. ', ';
            else
                $result .= $title->title. ', ';
        }

        return substr($result, 0, -2);
    }

    public function getPictureFilenameAttribute()
    {
        return strtolower($this->last_name.'-'.$this->first_name.'-'.mt_rand(9999,100000).'.png');
    }

    public function getProfilePictureUrlAttribute()
    {
        if($this->picture_id)
            return asset("/storage/accounts/members/".$this->profilePicture->filename);
        else
            return asset("/storage/accounts/members/default.png");
    }

    public function getAboutStoryAttribute()
    {
        return $this->story->description;
    }

    // Custom Function -------------------------------------------------------------------------------------------------
    /**
     * Offset members picture in the Directory
     * @param $value
     * @return null|string
     */
    public static function offset($value)
    {
        if ($value == 3)
            return null;
        elseif ($value == 2)
            return "col-md-offset-2";
        elseif ($value == 1)
            return "col-md-offset-4";
        else
            return null;
    }


}

app/Http/Controllers/Admin/Accounts/AddressController.php
<?php

namespace App\Http\Controllers\Admin\Accounts;

use App\User;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Address;

class AddressController extends IndexController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Load user data
        $user = User::find(request()->get('id'));
            $countries = parent::countries();
            $states = parent::states();
            $visibility = parent::visibility();
            $addressTypes = parent::addressType();
        return view('admin.accounts.address.create', compact('user', 'countries', 'states', 'visibility', 'addressTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Requests\AddressRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\AddressRequest $request)
    {
        Address::create(array_filter($request->all()));

        return redirect("/admin/accounts/users/". $request['user_id'])->with('message_success', 'The address has been added to the account.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $address = Address::find($id);
        $user = $address->user;
        $countries = parent::countries();
        $states = parent::states();
        $visibility = parent::visibility();
        $addressTypes = parent::addressType();

        return view('admin.accounts.address.edit', compact('user', 'address', 'countries', 'states', 'visibility', 'addressTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Requests\AddressRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\AddressRequest $request, $id)
    {
        $address = Address::find($id);
            $address->update(array_filter($request->all()));

        return redirect("/admin/accounts/users/" . $address->user_id)->with('message_success', 'The address has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/accounts/members/backBtn.blade.php
<a href="{{ url("/admin/accounts/members") }}" class="btn btn-primary aBtn" data-toggle="tooltip" data-placement="top" title="back to members list">
    <i class="fa fa-fw fa-angle-double-left" aria-hidden="true"></i> Back
</a>

resources/views/admin/accounts/members/create.blade.php
@extends('layouts.admin')

@section('title')
    Add new member
@endsection

@section('hTitle')
    Add new member for {{ $user->email }}
@endsection

@section('breadcrumbs')
    <li><a href="{{ url('admin/accounts/users') }}"><i class="fa fa-users"></i> Users Accounts</a></li>
    <li><a href="{{ url("admin/accounts/users/$user->id") }}"><i class="fa fa-user"></i> {{ $user->username }}</a></li>
    <li class="active">Add Member</li>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    {!! Form::open(['url' => '/admin/accounts/members', 'id' => 'myForm']) !!}
                    {!! Form::hidden('user_id', $user->id) !!}
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                                {!! Form::label('first_name', 'First name') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="required field"></i>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="your first name"><i class="fa fa-user fa-fw" aria-hidden="true"></i></span>
                                    {!! Form::text('first_name', null, ['class' => 'form-control input-lg', 'placeholder' => 'first name', 'autocomplete' => 'off', 'autofocus']) !!}
                                </div>
                                @if ($errors->has('first_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('first_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
                                {!! Form::label('last_name', 'Last name') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="required field"></i>
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="your last name"><i class="fa fa-user fa-fw" aria-hidden="true"></i></span>
                                    {!! Form::text('last_name', $user->username, ['class' => 'form-control input-lg', 'placeholder' => 'last name', 'autocomplete' => 'off']) !!}
                                </div>
                                @if ($errors->has('last_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('last_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('middle_name') ? ' has-error' : '' }}">
                                {!! Form::label('middle_name', 'Middle name') !!}
                                <div class="input-group input-group-lg">
                                    <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="your middle name"><i class="fa fa-user fa-fw" aria-hidden="true"></i></span>
                                    {!! Form::text('middle_name', null, ['class' => 'form-control input-lg', 'placeholder' => 'middle name', 'autocomplete' => 'off']) !!}
                                </div>
                                @if ($errors->has('middle_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('middle_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('dob') ? ' has-error' : '' }}">
                                {!! Form::label('dob', 'Birth Date') !!}
                                <div class="input-group date" data-provide="datepicker">
                                    <span class="input-group-addon"><i class="fa fa-calendar fa-fw" aria-hidden="true"></i></span>
                                    {!! Form::text('dob', null, ['class' => 'form-control', 'placeholder' => 'date', 'autocomplete' => 'off']) !!}
                                </div>
                                @if ($errors->has('dob'))
                                    <span class="help-block"><strong>{{ $errors->first('dob') }}</strong></span>
                                @endif
                            </div>
                        </div>
                    </div>
                    @include('admin.parts.btnSubmitCancel', ['btnName' => 'Save', 'cancelUrl' => URL::previous()])
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $('.date').datepicker({orientation: "bottom auto"});

            $('#myForm').on('submit', function(){
                $("#submitBtn").addClass('disabled').children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/admin/accounts/members/index.blade.php
@extends('layouts.admin')

@section('title')
    Members
@endsection

@section('hTitle')
    Community Church Members
@endsection

@section('breadcrumbs')
    <li><a href="{{ url("/admin/accounts/users") }}">Accounts</a></li>
    <li><a href="{{ url('admin/accounts/users') }}"><i class="fa fa-users"></i> Users Accounts</a></li>
    <li class="active">Members</li>
@endsection

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Total members <span class="badge">{{ $members->total() }}</span></h3>
            <div class="box-tools">
                <!-- search form -->
                {!! Form::open(['url' => '/api/user/search', 'id' => 'search', 'onsubmit' => 'return false;']) !!}
                <div class="input-group input-group-sm" style="width: 150px;">
                    {!! Form::text('search', null, ['class' => 'form-control pull-right', 'id' => 'searchQuery', 'placeholder' => 'Search...']) !!}
                    <span class="input-group-btn"><button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button></span>
                </div>
            {!! Form::close() !!}
            <!-- /.search form -->
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            <table class="table table-condensed table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Last Name</th>
                    <th>Name</th>
                    <th>Date of birth</th>
                    <th></th>
                </tr>
                </thead>
                <tbody id="result">
                @foreach($members as $member)
                    <tr>
                        <td>{{ $i++ }}</td>
                        <td>{{ $member->userAccount->username }}</td>
                        <td>
                            <a href="{{ url("/admin/accounts/members/$member->id") }}" class="btn btn-link btn-xs aBtn" data-toggle="tooltip" data-placement="top" title="view details">
                                <i class="fa fa-fw fa-user" aria-hidden="true"></i> {{ $member->full_name }}</a>
                        </td>
                        <td>{!! $member->birth_date !!}</td>
                        <td>
                            <a href="{{ url("/admin/accounts/members/$member->id") }}" class="btn btn-default btn-xs aBtn" data-toggle="tooltip" data-placement="left" title="view details">
                                <i class="fa fa-fw fa-eye" aria-hidden="true"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix" id="pagination">
            <div class="row">
                <div class="col-sm-5">
                    <div class="dataTables_info" id="dataTables-example_info" role="status" aria-live="polite">Showing {{ $members->firstItem() }} to {{ $members->lastItem() }} of {{ $members->total() }} accounts</div>
                </div>
                <div class="col-sm-7">
                    {{ $members->links('vendor.pagination.admin-lte') }}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        // Search function
        (function () {
            let submitBtn = document.getElementById('search-btn');
            submitBtn.onclick = function () {
                submitBtn.setAttribute("disabled", "disabled");
                let query = document.getElementById('searchQuery').value;
                axios.post('/api/member/search', {
                    query : query
                })
                    .then(function (response) {
                        document.getElementById('result').innerHTML = response.data;
                        submitBtn.removeAttribute("disabled");
                        document.getElementById('pagination').remove();
                    })
                    .catch(function (err) {
                        document.getElementById('result').innerHTML = err.message;
                    });
            }
        })();
    </script>
@endsection

resources/views/admin/accounts/members/undoBtn.blade.php
{!! Form::open(['action' => ['Admin\Accounts\MemberController@undo', $member->id]]) !!}
<button type="submit" class="btn btn-link">
    <i class="fa fa-fw fa-undo" aria-hidden="true"></i> Undo
</button>
{!! Form::close() !!}