routes/web.php
    Route::get('/church', 'Master\AboutController@church')->name('about.church');
    Route::get('/staff', 'Master\AboutController@staff')->name('about.staff');
    Route::get('/staff/{slug}', 'Master\AboutController@show')->name('about.staff.show');
    Route::get('/leaders', 'Master\AboutController@leaders')->name('about.leaders');
    Route::get('/leaders/{slug}', 'Master\AboutController@show')->name('about.leaders.show');
    Route::get('/bylaws', 'Master\AboutController@doc')->name('about.bylaws');
    Route::get('/contact-us', 'Master\ContactUsController@index')->name('about.contact');

    Route::group(['prefix' => 'committees'], function () {
        Route::get('/', 'Master\Committees\IndexController@index')->name('about.committees');
        Route::get('/{slug}', 'Master\Committees\IndexController@show')->name('about.committees.show');
    });
});

// Old Routes
Route::group(['prefix' => 'current'], function () {
    Route::get('/news', function () { return redirect(route('happenings.news_events')); });
    Route::get('/events', function () { return redirect(route('happenings.news_events')); });
    Route::get('/calendar', function () { return redirect(route('happenings.calendar')); });
});

Route::group(['prefix' => 'happenings'], function () {
    Route::get('/', 'Master\Happenings\IndexController@index')->name('happenings');
    //NEWS
    Route::get('news', 'Master\Happenings\NewsController@index')->name('happenings.news.index');
    Route::get('news/{slug}', 'Master\Happenings\NewsController@show')->name('happenings.news.show');
    //EVENTS
    Route::get('events', 'Master\Happenings\EventsController@index')->name('happenings.events.index');
    Route::get('events/{slug}', 'Master\Happenings\EventsController@show')->name('happenings.event.show');
    //CALENDAR
    Route::get('calendar', 'Master\Happenings\IndexController@calendar')->name('happenings.calendar');
});

// Old Routes
Route::group(['prefix' => 'ministry'], function () {
    Route::get('/missions', function () { return redirect(route('ministries.missions')); });
    Route::get('/mans', function () { return redirect(route('ministries.mens')); });
    Route::get('/womans', function () { return redirect(route('ministries.womens')); });
    Route::get('/care', function () { return redirect(route('ministries.care')); });
});

Route::group(['prefix' => 'ministries'], function () {
    Route::get('/', 'Master\Ministries\IndexController@index')->name('ministries');
    Route::get('/missions/member/{slug}', 'Master\Ministries\MissionsController@member')->name('ministries.missions.member');
    Route::get('/missions/{slug}', 'Master\Ministries\MissionsController@ministry')->name('ministries.missions.ministry');
    Route::get('/missions', 'Master\Ministries\MissionsController@index')->name('ministries.missions');
    Route::get('/mens', 'Master\Ministries\MensController@index')->name('ministries.mens');
    Route::get('/women', 'Master\Ministries\WomensController@index')->name('ministries.womens');
    Route::get('/women/{slug}', 'Master\Ministries\WomensController@show')->name('ministries.womens.show');
    Route::get('/care/{slug}', 'Master\Ministries\CareController@ministry')->name('ministries.care.ministry');
    Route::get('/care', 'Master\Ministries\CareController@index')->name('ministries.care');
});
Route::get('/give', 'Master\GiveController@index')->name('give');
Route::get('/photoalbums/{slug}', 'Master\PhotoalbumsController@show')->name('photoalbums.show');
Route::get('/photoalbums', 'Master\PhotoalbumsController@index')->name('photoalbums');


Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/directory', 'Master\Directory\IndexController@index')->name('directory');
    Route::get('/directory/member/{id}', 'Master\Directory\IndexController@show')->name('directory.member');

    Route::get('profile', 'Master\User\IndexController@index')->name('profile');
});

//Admin routes----------------------------------------------------------------------------------------------------------
Route::group(['prefix' => 'admin'], function(){

    Route::get('check', function(){
        return new App\Mail\AdministratorPasswordChanged(App\Admin::find(1), '123456');
    });

    Route::group(['middleware' => ['guest:admin']], function () {
        Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'Admin\Auth\LoginController@login')->name('admin.login.submit');
        //Reset Admin Password
        Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.password.update');
        Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
    });

    Route::group(['middleware' => ['auth:admin', 'pchecker']], function () {
        Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');
        Route::get('/', 'Admin\Dashboard\IndexController@index')->name('admin.dashboard');
        Route::get('/dashboard', function () { return redirect('/admin');});

        //Search for member
        Route::post('/search/member/', 'Admin\SearchController@getMember');
        //Documents
        Route::resource('/documents', 'Admin\Docs\IndexController');
        //Committees
        Route::resource('/committees', 'Admin\Committees\IndexController');
        Route::resource('/committees/member', 'Admin\Committees\MembersController');
        //Ministries
        Route::resource('/ministries', 'Admin\Ministries\IndexController');
        Route::resource('/ministries/member', 'Admin\Ministries\MembersController', ['except' =>['index', 'show']]);
        Route::resource('/ministries/liaison', 'Admin\Ministries\LiaisonsController', ['except' =>['index', 'show']]);
        //Empowerment
        Route::resource('groups/{id}/member', 'Admin\Empowerment\MembersController', ['except' =>['index', 'show', 'edit']]);
        Route::resource('groups', 'Admin\Empowerment\GroupsController');

        //Videos
        Route::resource('/videos', 'Admin\Video\IndexController');
        //Events
        Route::group(['prefix' => 'events'], function () {
            Route::resource('/meta/location', 'Admin\Events\LocationController', ['except' => ['index', 'show']]);
            Route::resource('/meta', 'Admin\Events\MetaController', ['except' => ['show']]);
            Route::resource('/members', 'Admin\Events\MembersController', ['only' => ['create', 'store', 'destroy']]);
            Route::resource('/price', 'Admin\Events\PriceController', ['except' => ['index', 'show']]);
            Route::resource('/picture', 'Admin\Events\PictureController', ['only' =>['create', 'store', 'destroy']]);
        });
        Route::resource('/events', 'Admin\Events\IndexController');
        //News
        Route::resource('/news/picture', 'Admin\News\PictureController', ['only' =>['create', 'store', 'destroy']]);
        Route::resource('/news', 'Admin\News\IndexController');
        //Sermons
        Route::resource('/sermons', 'Admin\Sermons\IndexController');
        Route::group(['prefix' => 'sermons'], function () {
            Route::post('/search/related', 'Admin\Sermons\SearchController@related');
            Route::resource('/file', 'Admin\Sermons\FileController');
            Route::resource('/relation', 'Admin\Sermons\RelationController', ['only' =>['edit', 'update', 'destroy']]);
        });
        //Photoalbum
        Route::resource('/photoalbums', 'Admin\Photoalbum\IndexController');
        Route::group(['prefix' => 'photoalbums'], function () {
            Route::resource('/pictures', 'Admin\Photoalbum\PictureController');
        });
        //Picture
        //Route::resource('/pictures', 'Admin\Pictures\IndexController');
        //Route::group(['prefix' => 'pictures'], function () {
            //Route::post('/search/related', 'Admin\Sermons\SearchController@related');
        //});

        //Accounts
        Route::group(['prefix' => 'accounts'], function () {

            Route::get('/', function () { return redirect('/admin/accounts/users');});

            Route::resource('/admins/password', 'Admin\Accounts\AdminsPasswordController', ['only' =>['edit', 'update']]);
            Route::resource('/admins', 'Admin\Accounts\AdminsController');

            Route::match(['get', 'post'], '/users/{id}/verify', 'Admin\Accounts\UserController@verifyUser');
            Route::post('/users/{id}/reset-password', 'Admin\Accounts\IndexController@resetPassword');

            Route::resource('/users', 'Admin\Accounts\UserController');
            Route::group(['prefix' => 'users'], function () {
                Route::resource('/picture', 'Admin\Accounts\UserPictureController');
                Route::resource('/address', 'Admin\Accounts\AddressController');
                Route::resource('/phone', 'Admin\Accounts\HomePhoneController');
                Route::resource('/story', 'Admin\Accounts\UserStoryController', ['except' =>['index', 'show']]);
            });

            Route::resource('/members', 'Admin\Accounts\MemberController');
            Route::group(['prefix' => 'members'], function () {
                Route::resource('/picture', 'Admin\Accounts\MemberPictureController');
                Route::resource('/phone', 'Admin\Accounts\PhoneController');
                Route::resource('/email', 'Admin\Accounts\EmailController');
                Route::resource('/title', 'Admin\Accounts\MembersTitleController');
                Route::resource('/story', 'Admin\Accounts\MemberStoryController', ['except' =>['index', 'show']]);

app/Photoalbum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
//use Illuminate\Database\Eloquent\SoftDeletes;

class Photoalbum extends Model
{
    //use SoftDeletes;
    //protected $dates = ['deleted_at'];

    protected $fillable = [
        'title', 'description', 'date', 'location_id', 'admin_id', 'picture_id', 'folder_name', 'slug'
    ];

    public function locationName()
    {
        return $this->belongsTo('App\AddressName', 'location_id', 'address_id');
    }

    public function pictures()
    {
        return $this->belongsToMany('App\Picture', 'picture_photoalbums', 'photoalbum_id', 'picture_id');
    }

    public function picture()
    {
        return $this->belongsTo('App\Picture','picture_id');
    }

    public function ministries()
    {
        return $this->belongsToMany('App\Ministry', 'ministry_photoalbums', 'photoalbum_id', 'ministry_id');
    }

    // Mutators --------------------------------------------------------------------------------------------------------
    public function setDateAttribute($value)
    {
        $this->attributes['date'] = date("Y-m-d", strtotime($value));
    }

    public function setSlugAttribute($value)
    {
        $shuffleString = substr(str_shuffle(rand().'qwertyuiopasdfghjklzxcvbnm'.rand()),0,5);
        $this->attributes['slug'] = str_slug($value, '-').'-'.$shuffleString;
    }

    // Accessors -------------------------------------------------------------------------------------------------------
    public function getDateAttribute($value)
    {
        return date("m/d/Y", strtotime($value));
    }

    public function getYearAttribute()
    {
        return date("Y", strtotime($this->date));
    }

    public function getAlbumUrlAttribute()
    {
        $year = date('Y', strtotime($this->date));
        $folder = $this->folder_name;

        return "storage/photoalbums/$year/$folder/";
    }

    public function getUrlAttribute()
    {
        return url("photoalbums/$this->slug");
    }

    public function getAlbumThumbnailUriAttribute()
    {
        if($this->picture_id)
            return asset($this->album_url.'thumbnails/'.$this->picture->filename);
        else
            return asset('storage/photoalbums/blank.png');
    }
}

app/Http/Controllers/Admin/Photoalbum/IndexController.php
<?php

namespace App\Http\Controllers\Admin\Photoalbum;

use App\Photoalbum;
use App\AddressType;
use App\Ministry;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    public function index()
    {
        $photoalbums = Photoalbum::orderBy('date', 'desc')->paginate();
        session()->put('pageId', $photoalbums->currentPage());
        $i = $photoalbums->firstItem();

        return view('admin.photoalbum.index', compact('photoalbums', 'i'));
    }

    public function create()
    {
        $locations = AddressType::find(3)->addresses;
        $ministries = Ministry::where('ministry_type_id', 1)->orderBy('name')->get();
        return view('admin.photoalbum.create', compact('locations', 'ministries'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'date' => 'required'
        ]);

        $request['slug'] = $request->title;
        $request['admin_id'] = request()->user()->id;
        $album = Photoalbum::create($request->all());
        if($request->ministry_id)
            $album->ministries()->sync($request->ministry_id);

        return redirect("admin/photoalbums/$album->id");
    }

    public function show($id)
    {
        $album = Photoalbum::findOrFail($id);
        return view('admin.photoalbum.show', compact('album'));
    }

    public function edit($id)
    {
        $album = Photoalbum::findOrFail($id);
        $locations = AddressType::find(3)->addresses;
        $ministries = Ministry::where('ministry_type_id', 1)->orderBy('name')->get();

        //dd($album->ministries);

        return view('admin.photoalbum.edit', compact('album', 'locations', 'ministries'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'date' => 'required'
        ]);

        $album = Photoalbum::findOrFail($id);
        $album->update($request->all());

        return redirect("admin/photoalbums/$album->id");
    }

    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Master/PhotoalbumsController.php
<?php

namespace App\Http\Controllers\Master;

use App\Photoalbum;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PhotoalbumsController extends Controller
{
    public function index()
    {
        $photoalbums = Photoalbum::orderBy('date', 'desc')->paginate(6);

        return view('master.photoalbums.index', compact('photoalbums'));
    }

    public function show($slug)
    {
        $album = Photoalbum::whereSlug($slug)->first();

        return view('master.photoalbums.show', compact('album'));
    }
}

resources/views/admin/photoalbum/create.blade.php
@extends('layouts.admin')

@section('title', 'Add New Photoalbum')

@section('hTitle')
    Add New Photoalbum
@endsection

@section('breadcrumbs')
    <li><a href="{{ url('/admin/photoalbums') }}">Photoalbums</a></li>
    <li class="active">Add New Photoalbum</li>
@endsection

@section('content')
    <div class="box box-primary">
        {!! Form::open(['url' => 'admin/photoalbums', 'id' => 'myForm']) !!}
        <div class="box-body">
            @include('admin.photoalbum.formBody')
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            @include('admin.parts.btnSubmitCancel', ['btnName' => 'Save', 'cancelUrl' => url('/admin/photoalbums')])
        </div>
        {!! Form::close() !!}
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $("#datepicker").datetimepicker({format: 'MM/DD/YYYY'});

            $('#myForm').on('submit', function(){
                $('#submitBtn').addClass('disabled').children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/admin/photoalbum/edit.blade.php
@extends('layouts.admin')

@section('title', 'Edit Photoalbum')

@section('hTitle')
    Edit Photoalbum
@endsection

@section('breadcrumbs')
    <li><a href="{{ url('/admin/photoalbums') }}">Photoalbums</a></li>
    <li class="active">Add New Photoalbum</li>
@endsection

@section('content')
    <div class="box box-primary">
        {!! Form::model($album, ['method' => 'PATCH', 'action' => ['Admin\Photoalbum\IndexController@update', $album->id], 'id' => 'myForm']) !!}
        <div class="box-body">
            @include('admin.photoalbum.formBody')
            <div class="form-group{{ $errors->has('picture_id') ? ' has-error' : '' }}">
                <h4>Album Thumbnail {{ $album->picture_id }}</h4>
                @foreach($album->pictures as $picture)
                    <div class="radio radio-inline">
                        <label>
                            @if($album->picture_id == $picture->id)
                                {!! Form::radio('picture_id', $picture->id, true); !!}
                            @else
                                {!! Form::radio('picture_id', $picture->id); !!}
                            @endif
                            <img src="{{ asset("$album->album_url/thumbnails/$picture->filename") }}" alt="{{ $picture->alt or null }}" class="img-responsive" width="70">
                        </label>
                    </div>
                @endforeach
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            @include('admin.parts.btnSubmitCancel', ['btnName' => 'Save', 'cancelUrl' => url('/admin/photoalbums')])
        </div>
        {!! Form::close() !!}
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $("#datepicker").datetimepicker({format: 'MM/DD/YYYY'});

            $('#myForm').on('submit', function(){
                $('#submitBtn').addClass('disabled').children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/admin/photoalbum/formBody.blade.php
<div class="row">
    <div class="col-lg-6">
        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
            {!! Form::label('title', 'Title') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="required field"></i>
            <div class="input-group input-group-lg">
                <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="Sermon's title"><i class="fa fa-chevron-right fa-fw" aria-hidden="true"></i></span>
                {!! Form::text('title', null, ['class' => 'form-control input-lg', 'placeholder' => 'sermons title', 'id' => 'title', 'autocomplete' => 'off']) !!}
            </div>
            @if ($errors->has('title'))
                <span class="fa fa-exclamation-triangle form-control-feedback" aria-hidden="true"></span>
                <span class="sr-only">(error)</span>
                <span class="help-block"><strong>{{ $errors->first('title') }}</strong></span>
            @endif
        </div>
        <div class="form-group{{ $errors->has('date') ? ' has-error' : '' }}">
            {!! Form::label('date', 'Date') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="required field"></i>
            <div class="input-group input-group-lg date" id="datepicker">
                <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="date when the video was recorded"><i class="fa fa-calendar fa-fw" aria-hidden="true"></i></span>
                {!! Form::text('date', null, ['class' => 'form-control input-lg', 'placeholder' => 'photo session date', 'autocomplete' => 'off']) !!}
            </div>
            @if ($errors->has('date'))<span class="help-block"><strong>{{ $errors->first('date') }}</strong></span>@endif
        </div>
        @include('admin.parts.textarea', ['name' => 'description', 'title' => 'Photoalbum Description'])
    </div>
    <div class="col-lg-6">
        <div class="form-group{{ $errors->has('location_id') ? ' has-error' : '' }}">
            {!! Form::label('event-location', 'Event Location') !!}
            <div class="row">
                @foreach($locations as $location)
                    <div class="col-lg-2">
                        <div class="radio">
                            <label>
                                {!! Form::radio('location_id', $location->id) !!}
                                <strong>{{ $location->addressName->name }}</strong><br>
                                {{ $location->address1 }}<br>{{ $location->city }}, {{ $location->state->name }} {{ $location->zip_code }}
                            </label>
                        </div>
                    </div>
                @endforeach

                @if ($errors->has('location_id'))
                    <span class="help-block"><strong>{{ $errors->first('location_id') }}</strong></span>
                @endif
            </div>
        </div>
        <div class="form-group{{ $errors->has('ministry_id') ? ' has-error' : '' }}">
            {!! Form::label('ministry_id', 'Ministries') !!}
            @foreach($ministries as $ministry)
                <div class="radio">
                    <label>
                        {!! Form::checkbox("ministry_id[$ministry->id]", $ministry->id) !!}
                        <strong>{{ $ministry->name }}</strong>
                    </label>
                </div>
            @endforeach
            @if ($errors->has('ministry_id'))<span class="help-block"><strong>{{ $errors->first('ministry_id') }}</strong></span>@endif
        </div>
    </div>
</div>

resources/views/admin/photoalbum/index.blade.php
@extends('layouts.admin')

@section('title', 'Photoalbums')

@section('hTitle')
    Photoalbums
@endsection

@section('breadcrumbs')
    <li class="active">Photoalbums</li>
@endsection

@section('content')
<div class="box box-primary">
    <div class="box-header with-border">
        Total <span class="badge">{{ $photoalbums->total() }}</span>
        <a href="{{ url('admin/photoalbums/create') }}" class="btn btn-primary btn-xs aBtn" data-toggle="tooltip" data-placement="top" title="create new photoalbum">
            <i class="fa fa-fw fa-plus-circle" aria-hidden="true"></i> Add</a>
    </div>
    <!-- /.box-header -->
    <div class="box-body no-padding table-responsive">
        @include('admin.parts.message')
        <table class="table table-condensed table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th></th>
                <th>Title</th>
                <th>Location</th>
                <th colspan="3"></th>
            </tr>
            </thead>
            <tbody id="result">
            @foreach($photoalbums as $album)
                <tr>
                    <td scope="col">{{ $i++ }}</td>
                    <td>{{ $album->date }}</td>
                    <td><a href="{{ url("/admin/photoalbums/$album->id") }}" data-toggle="tooltip" data-placement="left" title="view details"><img src="{{ $album->album_thumbnail_uri }}" alt="" width="20"></a></td>
                    <td><a href="{{ url("/admin/photoalbums/$album->id") }}">{{ $album->title }}</a></td>
                    <td>{{ $album->locationName->name }}</td>
                    <td class="text-center">
                        <a class="btn btn-default btn-xs aBtn" href="{{ url("/admin/photoalbums/$album->id") }}" data-toggle="tooltip" data-placement="left" title="view details">
                            <i class="fa fa-fw fa-eye" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td class="text-center">
                        <a class="btn btn-primary btn-xs aBtn" href="{{ url("/admin/photoalbums/$album->id/edit") }}" data-toggle="tooltip" data-placement="left" title="edit">
                            <i class="fa fa-fw fa-pencil" aria-hidden="true"></i>
                        </a>
                    </td>
                    <td class="text-right">
                        @include('admin.parts.deleteBtn', ['action' => ['Admin\Photoalbum\IndexController@destroy', $album->id], 'class' => 'btn-xs', 'btnTitle' => "Delete $album->title"])
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer clearfix">{{ $photoalbums->links('vendor.pagination.admin-lte') }}</div>
</div>
@endsection

resources/views/admin/photoalbum/show.blade.php
@extends('layouts.admin')

@section('title', $album->title)

@section('hTitle')
    Photoalbum: {{ $album->title }} <small>{{ $album->date }}</small>
@endsection

@section('breadcrumbs')
    <li><a href="{{ url('/admin/photoalbums') }}">Photoalbums</a></li>
    <li class="active">{{ $album->title }}</li>
@endsection

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            {{ $album->title }} <span class="badge" data-toggle="tooltip" data-placement="top" title="Total pictures">{{ $album->pictures->count() }}</span>
            <a class="btn btn-primary btn-xs aBtn pull-right" href="{{ url("admin/photoalbums/$album->id/edit") }}" data-toggle="tooltip" data-placement="top" title="edit photo album's info"><i class="fa fa-fw fa-pencil"></i> Edit</a></div>
        <!-- /.box-header -->
        <div class="box-body">
            {!! $album->description or 'n/a' !!}
            <div class="row">
                @foreach($album->pictures as $picture)
                    <div class="col-md-2 text-center">
                        <a href="{{ asset($album->album_url.$picture->filename) }}" target="_blank">
                            <img src="{{ asset("$album->album_url/thumbnails/$picture->filename") }}" alt="{{ $picture->alt or null }}" class="img-responsive">
                        </a>
                        @include('admin.parts.deleteBtn', ['action' => ['Admin\Photoalbum\PictureController@destroy', $picture->id], 'class' => 'btn-xs', 'btnTitle' => "Delete", 'position' => 'top'])
                    </div>
                @endforeach
            </div>
            <br>
            <a href="{{ url("admin/photoalbums/pictures/create?id=$album->id") }}" class="btn btn-block btn-primary aBtn" data-toggle="tooltip" data-placement="top" title="upload file">
                <i class="fa fa-upload fa-fw"></i> Upload
            </a>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix"></div>
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $('[data-toggle=confirmation]').confirmation({
                rootSelector: '[data-toggle=confirmation]'
            });
        });
    </script>
@endsection