routes/web.php
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', function () {
    return redirect(route('home'));
});

Route::get('/', 'Master\Home\IndexController@index')->name('home');

Route::get('/phpinfo', 'Master\Home\IndexController@pinfo');

Route::group(['prefix' => 'media'], function () {
    Route::get('/', 'Master\Media\IndexController@index')->name('media');
    Route::group(['prefix' => 'videos'], function () {
        Route::get('/', 'Master\Media\VideoController@index')->name('media.videos');
        Route::get('/category/{category_slug}', 'Master\Media\VideoCategoriesController@category')->name('media.videos.category');
        Route::get('/category/{category_slug}/{video_slug}', 'Master\Media\VideoCategoriesController@category_video')->name('media.videos.category.video');
        Route::get('/pastor/{name}', 'Master\Media\VideoCategoriesController@pastor')->name('media.videos.pastor');
        Route::get('/pastor/{name}/{video_slug}', 'Master\Media\VideoCategoriesController@pastor_video')->name('media.videos.pastor.show');
        Route::get('/search', 'Master\Media\VideoController@search')->name('media.video.search');
        Route::get('/{slug}', 'Master\Media\VideoController@show')->name('media.video.show');
    });

    Route::group(['prefix' => 'sermons'], function () {
        Route::get('/', 'Master\Media\SermonController@index')->name('media.sermons');
        Route::get('/pastor/{name}', 'Master\Media\SermonCategoriesController@pastor')->name('media.sermons.pastor');
        Route::get('/pastor/{name}/{sermon_slug}', 'Master\Media\SermonCategoriesController@pastor_sermon')->name('media.sermons.pastor.show');
        Route::get('/search', 'Master\Media\SermonController@search')->name('media.sermon.search');
        Route::get('/{slug}', 'Master\Media\SermonController@show')->name('media.sermon.show');
    });
});

Route::group(['prefix' => 'about'], function () {
    Route::get('/', 'Master\AboutController@index')->name('about');
    Route::get('/church', 'Master\AboutController@church')->name('about.church');
    Route::get('/staff', 'Master\AboutController@staff')->name('about.staff');
    Route::get('/staff/{slug}', 'Master\AboutController@show')->name('about.staff.show');
    Route::get('/leaders', 'Master\AboutController@leaders')->name('about.leaders');
    Route::get('/leaders/{slug}', 'Master\AboutController@show')->name('about.leaders.show');
    Route::get('/bylaws', 'Master\AboutController@doc')->name('about.bylaws');
    Route::get('/contact-us', 'Master\ContactUsController@index')->name('about.contact');

    Route::group(['prefix' => 'committees'], function () {
        Route::get('/', 'Master\Committees\IndexController@index')->name('about.committees');
        Route::get('/{slug}', 'Master\Committees\IndexController@show')->name('about.committees.show');
    });
});

// Old Routes
Route::group(['prefix' => 'current'], function () {
    Route::get('/news', function () { return redirect(route('happenings.news_events')); });
    Route::get('/events', function () { return redirect(route('happenings.news_events')); });
    Route::get('/calendar', function () { return redirect(route('happenings.calendar')); });
});

Route::group(['prefix' => 'happenings'], function () {
    Route::get('/', 'Master\Happenings\IndexController@index')->name('happenings');
    //NEWS
    Route::get('news', 'Master\Happenings\NewsController@index')->name('happenings.news.index');
    Route::get('news/{slug}', 'Master\Happenings\NewsController@show')->name('happenings.news.show');
    //EVENTS
    Route::get('events', 'Master\Happenings\EventsController@index')->name('happenings.events.index');
    Route::get('events/{slug}', 'Master\Happenings\EventsController@show')->name('happenings.event.show');
    //CALENDAR
    Route::get('calendar', 'Master\Happenings\IndexController@calendar')->name('happenings.calendar');
});

// Old Routes
Route::group(['prefix' => 'ministry'], function () {
    Route::get('/missions', function () { return redirect(route('ministries.missions')); });
    Route::get('/mans', function () { return redirect(route('ministries.mens')); });
    Route::get('/womans', function () { return redirect(route('ministries.womens')); });
    Route::get('/care', function () { return redirect(route('ministries.care')); });
});

Route::group(['prefix' => 'ministries'], function () {
    Route::get('/', 'Master\Ministries\IndexController@index')->name('ministries');
    Route::get('/missions/member/{slug}', 'Master\Ministries\MissionsController@member')->name('ministries.missions.member');
    Route::get('/missions/{slug}', 'Master\Ministries\MissionsController@ministry')->name('ministries.missions.ministry');
    Route::get('/missions', 'Master\Ministries\MissionsController@index')->name('ministries.missions');
    Route::get('/mens', 'Master\Ministries\MensController@index')->name('ministries.mens');
    Route::get('/women', 'Master\Ministries\WomensController@index')->name('ministries.womens');
    Route::get('/women/{slug}', 'Master\Ministries\WomensController@show')->name('ministries.womens.show');
    Route::get('/care/{slug}', 'Master\Ministries\CareController@ministry')->name('ministries.care.ministry');
    Route::get('/care', 'Master\Ministries\CareController@index')->name('ministries.care');
});
Route::get('/give', 'Master\GiveController@index')->name('give');
Route::get('/photoalbums/{slug}', 'Master\PhotoalbumsController@show')->name('photoalbums.show');
Route::get('/photoalbums', 'Master\PhotoalbumsController@index')->name('photoalbums');


Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/directory', 'Master\Directory\IndexController@index')->name('directory');
    Route::get('/directory/member/{id}', 'Master\Directory\IndexController@show')->name('directory.member');

    Route::get('profile', 'Master\User\IndexController@index')->name('profile');
});

//Admin routes----------------------------------------------------------------------------------------------------------
Route::group(['prefix' => 'admin'], function(){

    Route::get('check', function(){
        return new App\Mail\AdministratorPasswordChanged(App\Admin::find(1), '123456');
    });

    Route::group(['middleware' => ['guest:admin']], function () {
        Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'Admin\Auth\LoginController@login')->name('admin.login.submit');
        //Reset Admin Password
        Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.password.update');
        Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
    });

    Route::group(['middleware' => ['auth:admin', 'pchecker']], function () {
        Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');
        Route::get('/', 'Admin\Dashboard\IndexController@index')->name('admin.dashboard');
        Route::get('/dashboard', function () { return redirect('/admin');});

        //Search for member
        Route::post('/search/member/', 'Admin\SearchController@getMember');
        //Documents
        Route::resource('/documents', 'Admin\Docs\IndexController');
        //Committees
        Route::resource('/committees', 'Admin\Committees\IndexController');
        Route::resource('/committees/member', 'Admin\Committees\MembersController');
        //Ministries
        Route::resource('/ministries', 'Admin\Ministries\IndexController');
        Route::resource('/ministries/member', 'Admin\Ministries\MembersController', ['except' =>['index', 'show']]);
        Route::resource('/ministries/liaison', 'Admin\Ministries\LiaisonsController', ['except' =>['index', 'show']]);
        //Empowerment
        Route::resource('groups/{id}/member', 'Admin\Empowerment\MembersController', ['except' =>['index', 'show', 'edit']]);
        Route::resource('groups', 'Admin\Empowerment\GroupsController');

        //Videos
        Route::resource('/videos', 'Admin\Video\IndexController');
        //Events
        Route::group(['prefix' => 'events'], function () {
            Route::resource('/meta/location', 'Admin\Events\LocationController', ['except' => ['index', 'show']]);
            Route::resource('/meta', 'Admin\Events\MetaController', ['except' => ['show']]);
            Route::resource('/members', 'Admin\Events\MembersController', ['only' => ['create', 'store', 'destroy']]);
            Route::resource('/price', 'Admin\Events\PriceController', ['except' => ['index', 'show']]);
            Route::resource('/picture', 'Admin\Events\PictureController', ['only' =>['create', 'store', 'destroy']]);
        });
        Route::resource('/events', 'Admin\Events\IndexController');
        //News
        Route::resource('/news/picture', 'Admin\News\PictureController', ['only' =>['create', 'store', 'destroy']]);
        Route::resource('/news', 'Admin\News\IndexController');
        //Sermons
        Route::resource('/sermons', 'Admin\Sermons\IndexController');
        Route::group(['prefix' => 'sermons'], function () {
            Route::post('/search/related', 'Admin\Sermons\SearchController@related');
            Route::resource('/file', 'Admin\Sermons\FileController');

app/Event.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $fillable = [
        'category_id', 'title', 'subtitle', 'slug', 'description', 'picture_id'
    ];

    public function ministries()
    {
        return $this->belongsToMany('App\Ministry', 'ministry_events', 'event_id','ministry_id');
    }

    public function dates()
    {
        return $this->hasMany('App\EventMeta', 'event_id','id')->where('date_time', '>', Carbon::now());
    }

    public function category()
    {
        return $this->belongsTo('App\Category', 'category_id');
    }

    public function members()
    {
        return $this->belongsToMany('App\Member', 'event_members', 'event_id','member_id')->withPivot('id', 'leader', 'title', 'order');
    }

    public function price()
    {
        return $this->hasOne('App\EventPrice', 'event_id');
    }

    public function picture()
    {
        return $this->belongsTo('App\Picture','picture_id');
    }

    // Mutators -------------------------------------------------------------------------------------------------------
    public function setSlugAttribute($value)
    {
        $shuffleString = substr(str_shuffle(rand().'qwertyuiopasdfghjklzxcvbnm'.rand()),0,5);

        $this->attributes['slug'] = str_slug($value, '-').'-'.$shuffleString;
    }

    // Accessors -------------------------------------------------------------------------------------------------------
    public function getMinistryNameAttribute()
    {
        if(is_null($this->ministries)) {
            return $this->ministries->first()->name;
        } else {
            return "Church Event";
        }
    }

    public function getTitleSubtitleAttribute()
    {
        if($this->subtitle) {
            return "$this->title <small>$this->subtitle</small>";
        } else {
            return "$this->title";
        }
    }

    public function getUrlAttribute()
    {
        return url("happenings/events/$this->slug");
    }

    public function getCategoryTitleAttribute()
    {
        return $this->category->title;
    }

    // Main leader/member for the event
    public function getMainMemberAttribute()
    {
        $members = $this->members;
        if($members)
            return $members->first();
        else
            return false;
    }

    public function getMainMemberTitleAttribute()
    {
        $members = $this->members;
        if($members)
            return $members->first();
        else
            return false;
    }

    public function getPriceDescriptionAttribute()
    {
        if($this->price->price) {
            $price = $this->price->price;
            $description = $this->price->name;
            return "$ $price, $description";
        } else {
            return false;
        }
    }

    public function getThumbnailPictureAttribute()
    {
        $year = date('Y', strtotime($this->created_at));
        if($this->picture_id)
            return asset("storage/events/$year/thumbnails/".$this->picture->filename);
        else
            return asset("storage/events/thumbnail-default.jpg");
    }

    // Custom ---------------------------------------------------------------------------------------------------------
    public static function current_date($day)
    {
        return strtotime(date("Y-m-$day"));
    }

    public static function text_limit($text, $start = 0, $strLength = 105)
    {
        //Remove any titles <h1> - <h6>
        $no_title_txt = preg_replace('/<h[0-6][^>]*>([\s\S]*?)<\/h[0-6][^>]*>/', '', $text);

        // Remove HTML tags from content
        $txt = strip_tags($no_title_txt);

        if(strlen($txt) > $strLength)
            $result = substr($txt, $start, strrpos($txt, " ", -(strlen($txt) - $strLength))); // Return trimmed string
        else
            $result = $txt;

        return $result;
    }
}

app/EventMeta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EventMeta extends Model
{
    protected $table = 'events_meta';

    protected $fillable = [
        'event_id', 'location_id', 'date_time', 'comments'
    ];

    public function data()
    {
        return $this->belongsTo('App\Event', 'event_id');
    }

    public function location()
    {
        return $this->belongsTo('App\Address', 'location_id');
    }

    // Mutators --------------------------------------------------------------------------------------------------------
    public function setDateTimeAttribute($value)
    {
        $this->attributes['date_time'] = date("Y-m-d H:i:s", strtotime($value));
    }

    // Accessors -------------------------------------------------------------------------------------------------------
    public function getDateTimeAttribute($value)
    {
        return date("m/d/y g:i A", strtotime($value));
    }

    public function getDateAttribute()
    {
        return date("l, F d, Y", strtotime($this->date_time));
    }

    public function getTimeAttribute()
    {
        return date("g:i A", strtotime($this->date_time));
    }

    public function getLocationNameAttribute()
    {
        if($this->location_id)
            return $this->location->addressName->name;
        else
            return "-TBD-";
    }
}

app/Http/Controllers/Admin/Events/LocationController.php
<?php

namespace App\Http\Controllers\Admin\Events;

use App\AddressType;
use App\EventMeta;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LocationController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $eventMeta = EventMeta::findOrFail(request()->id);
        $event = $eventMeta->data;
        $locations = AddressType::find(3)->addresses;
        return view('admin.events.location.create', compact('eventMeta', 'event', 'locations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'location_id' => 'required'
        ], [
            'location_id.required' => 'You need to specify the event location.'
        ]);

        $eventMeta = EventMeta::findOrFail($request->meta_id);
        $eventMeta->update(['location_id' => $request->location_id]);
        return redirect("admin/events/$eventMeta->event_id")->with('message_success', 'Event Location has been saved successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $eventMeta = EventMeta::findOrFail($id);
        $event = $eventMeta->data;
        $locations = AddressType::find(3)->addresses;
        return view('admin.events.location.edit', compact('eventMeta', 'event', 'locations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'location_id' => 'required'
        ], [
            'location_id.required' => 'You need to specify the event location.'
        ]);

        $eventMeta = EventMeta::findOrFail($id);
        $eventMeta->update(['location_id' => $request->location_id]);
        return redirect("admin/events/$eventMeta->event_id")->with('message_success', 'Event Location has been updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/master/happenings/events/index.blade.php
@extends('layouts.master')
@section('title', 'Events')
@section('content')
    @include('master.parts.breadcrumbs-template', [
        'bc' => Breadcrumbs::render('events'),
        'bc_title' => "Events",
        'bc_subtitle' => 'Community Church at Saddlebrooke'
    ])

    <!-- BEGIN: BLOG LISTING EVENTS -->
    <div class="c-content-box c-size-md">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="c-content-title-1">
                        <h3 class="c-left c-font-uppercase">Upcoming Events</h3>
                        <div class="c-line-left c-theme-bg"></div>
                    </div>
                    <div class="c-content-blog-post-1-list">
                        @foreach($events as $event)
                            <div class="c-content-blog-post-1">
                                <div class="c-media">
                                    <div class="item">
                                        <div class="c-content-media-2" style="background: url({{ $event->data->thumbnail_picture }}) no-repeat center center; background-size: cover; min-height: 360px;"></div>
                                    </div>
                                </div>
                                <div class="c-title c-font-bold c-font-uppercase">
                                    <a href="{{ $event->data->url }}">{!! $event->data->title_subtitle !!}</a>
                                </div>
                                <div class="c-desc">
                                    <!--{!! $event->data->text_limit($event->data->description, 0, 221) !!}...<a href="{{ url($event->data->url) }}" title="read more"><i class="fa fa-fw fa-angle-double-right"></i></a>-->
                                    {!! $event->data->description !!}
                                </div>
                                <div class="c-panel">
                                    <div class="c-author"><a href="#">By <span class="c-font-uppercase">CCSB</span></a></div>
                                    <div class="c-date">on <span class="c-font-uppercase">{{ $event->date }}</span> at <span class="c-font-uppercase">{{ $event->time }}</span></div>
                                    <ul class="c-tags c-theme-ul-bg">
                                        <li>{{ $event->data->category->title }}</li>
                                    </ul>
                                </div>
                            </div>
                        @endforeach
                        {{ $events->links('vendor.pagination.jango') }}
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </div>
@endsection

resources/views/master/happenings/events/show.blade.php
@extends('layouts.master')
@section('title', 'Events')
@section('content')
    @include('master.parts.breadcrumbs-template', [
        'bc' => Breadcrumbs::render('event_show', $event),
        'bc_title' => "$event->title",
        'bc_subtitle' => 'Community Church at Saddlebrooke'
    ])

    <!-- BEGIN: BLOG LISTING EVENTS -->
    <div class="c-content-box c-size-md">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="c-content-blog-post-1-list">
                        <div class="c-content-blog-post-1">
                            <div class="c-media">
                                <div class="item">
                                    <div class="c-content-media-2" style="background: url({{ asset("storage/events/thumbnail-default.jpg") }}) no-repeat center center; background-size: cover; min-height: 360px;"></div>
                                </div>
                            </div>
                            <div class="c-title c-font-bold c-font-uppercase">
                                {!! $event->title_subtitle !!}
                            </div>
                            <div class="c-desc">
                                {!! $event->description !!}

                                <ul class="c-content-list-1 c-theme">
                                    @foreach($dates as $date)
                                    <li class="c-bg-before-blue">{{ $date->date }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            <div class="c-panel">
                                <div class="c-author"><a>By <span class="c-font-uppercase">CCSB</span></a></div>
                                <ul class="c-tags c-theme-ul-bg">
                                    <li>{{ $event->category->title }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
    </div>

@endsection

resources/views/master/happenings/events/sidenav.blade.php
<!-- BEGIN: CONTENT/BLOG/BLOG-SIDEBAR-1 -->
<div class="c-content-ver-nav">
    <div class="c-content-title-1 c-theme c-title-md c-margin-t-40">
        <h3 class="c-font-bold c-font-uppercase">Archive</h3>
        <div class="c-line-left c-theme-bg"></div>
    </div>
    <ul class="c-menu c-arrow-dot1 c-theme">
        <!--<li><a href="#">Web Development(2)</a></li>
        <li><a href="#">UX Design(12)</a></li>
        <li><a href="#">Mobile Development(5)</a></li>
        <li><a href="#">Internet Marketing(7)</a></li>
        <li><a href="#">Social Networks(11)</a></li>
        <li><a href="#">Web Design(18)</a></li>-->
    </ul>
</div><!-- END: CONTENT/BLOG/BLOG-SIDEBAR-1 -->