routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/home', function () {
    return redirect(route('home'));
});

Route::get('/', 'Master\Home\IndexController@index')->name('home');

Route::get('/phpinfo', 'Master\Home\IndexController@pinfo');

Route::group(['prefix' => 'media'], function () {
    Route::get('/', 'Master\Media\IndexController@index')->name('media');
    Route::group(['prefix' => 'videos'], function () {
        Route::get('/', 'Master\Media\VideoController@index')->name('media.videos');
        Route::get('/category/{category_slug}', 'Master\Media\VideoCategoriesController@category')->name('media.videos.category');
        Route::get('/category/{category_slug}/{video_slug}', 'Master\Media\VideoCategoriesController@category_video')->name('media.videos.category.video');
        Route::get('/pastor/{name}', 'Master\Media\VideoCategoriesController@pastor')->name('media.videos.pastor');
        Route::get('/pastor/{name}/{video_slug}', 'Master\Media\VideoCategoriesController@pastor_video')->name('media.videos.pastor.show');
        Route::get('/search', 'Master\Media\VideoController@search')->name('media.video.search');
        Route::get('/{slug}', 'Master\Media\VideoController@show')->name('media.video.show');
    });

    Route::group(['prefix' => 'sermons'], function () {
        Route::get('/', 'Master\Media\SermonController@index')->name('media.sermons');
        Route::get('/pastor/{name}', 'Master\Media\SermonCategoriesController@pastor')->name('media.sermons.pastor');
        Route::get('/pastor/{name}/{sermon_slug}', 'Master\Media\SermonCategoriesController@pastor_sermon')->name('media.sermons.pastor.show');
        Route::get('/search', 'Master\Media\SermonController@search')->name('media.sermon.search');
        Route::get('/{slug}', 'Master\Media\SermonController@show')->name('media.sermon.show');
    });
});

Route::group(['prefix' => 'about'], function () {
    Route::get('/', 'Master\AboutController@index')->name('about');
    Route::get('/church', 'Master\AboutController@church')->name('about.church');
    Route::get('/staff', 'Master\AboutController@staff')->name('about.staff');
    Route::get('/staff/{slug}', 'Master\AboutController@show')->name('about.staff.show');
    Route::get('/leaders', 'Master\AboutController@leaders')->name('about.leaders');
    Route::get('/leaders/{slug}', 'Master\AboutController@show')->name('about.leaders.show');
    Route::get('/bylaws', 'Master\AboutController@doc')->name('about.bylaws');
    Route::get('/contact-us', 'Master\ContactUsController@index')->name('about.contact');

    Route::group(['prefix' => 'committees'], function () {
        Route::get('/', 'Master\Committees\IndexController@index')->name('about.committees');
        Route::get('/{slug}', 'Master\Committees\IndexController@show')->name('about.committees.show');
    });
});

// Old Routes
Route::group(['prefix' => 'current'], function () {
    Route::get('/news', function () { return redirect(route('happenings.news_events')); });
    Route::get('/events', function () { return redirect(route('happenings.news_events')); });
    Route::get('/calendar', function () { return redirect(route('happenings.calendar')); });
});

Route::group(['prefix' => 'happenings'], function () {
    Route::get('/', 'Master\Happenings\IndexController@index')->name('happenings');
    //NEWS
    Route::get('news', 'Master\Happenings\NewsController@index')->name('happenings.news.index');
    Route::get('news/{slug}', 'Master\Happenings\NewsController@show')->name('happenings.news.show');
    //EVENTS
    Route::get('events', 'Master\Happenings\EventsController@index')->name('happenings.events.index');
    Route::get('events/{slug}', 'Master\Happenings\EventsController@show')->name('happenings.event.show');
    //CALENDAR
    Route::get('calendar', 'Master\Happenings\IndexController@calendar')->name('happenings.calendar');
});

// Old Routes
Route::group(['prefix' => 'ministry'], function () {
    Route::get('/missions', function () { return redirect(route('ministries.missions')); });
    Route::get('/mans', function () { return redirect(route('ministries.mens')); });
    Route::get('/womans', function () { return redirect(route('ministries.womens')); });
    Route::get('/care', function () { return redirect(route('ministries.care')); });
});

Route::group(['prefix' => 'ministries'], function () {
    Route::get('/', 'Master\Ministries\IndexController@index')->name('ministries');
    Route::get('/missions/member/{slug}', 'Master\Ministries\MissionsController@member')->name('ministries.missions.member');
    Route::get('/missions/{slug}', 'Master\Ministries\MissionsController@ministry')->name('ministries.missions.ministry');
    Route::get('/missions', 'Master\Ministries\MissionsController@index')->name('ministries.missions');
    Route::get('/mens', 'Master\Ministries\MensController@index')->name('ministries.mens');
    Route::get('/women', 'Master\Ministries\WomensController@index')->name('ministries.womens');
    Route::get('/women/{slug}', 'Master\Ministries\WomensController@show')->name('ministries.womens.show');
    Route::get('/care/{slug}', 'Master\Ministries\CareController@ministry')->name('ministries.care.ministry');
    Route::get('/care', 'Master\Ministries\CareController@index')->name('ministries.care');
});
Route::get('/give', 'Master\GiveController@index')->name('give');
Route::get('/photoalbums/{slug}', 'Master\PhotoalbumsController@show')->name('photoalbums.show');
Route::get('/photoalbums', 'Master\PhotoalbumsController@index')->name('photoalbums');


Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/directory', 'Master\Directory\IndexController@index')->name('directory');
    Route::get('/directory/member/{id}', 'Master\Directory\IndexController@show')->name('directory.member');

    Route::get('profile', 'Master\User\IndexController@index')->name('profile');
});

//Admin routes----------------------------------------------------------------------------------------------------------
Route::group(['prefix' => 'admin'], function(){

    Route::get('check', function(){
        return new App\Mail\AdministratorPasswordChanged(App\Admin::find(1), '123456');
    });

    Route::group(['middleware' => ['guest:admin']], function () {
        Route::get('/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('/login', 'Admin\Auth\LoginController@login')->name('admin.login.submit');
        //Reset Admin Password
        Route::post('/password/email', 'Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
        Route::get('/password/reset', 'Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
        Route::post('/password/reset', 'Admin\Auth\ResetPasswordController@reset')->name('admin.password.update');
        Route::get('/password/reset/{token}', 'Admin\Auth\ResetPasswordController@showResetForm')->name('admin.password.reset');
    });

    Route::group(['middleware' => ['auth:admin', 'pchecker']], function () {
        Route::post('/logout', 'Admin\Auth\LoginController@logout')->name('admin.logout');
        Route::get('/', 'Admin\Dashboard\IndexController@index')->name('admin.dashboard');
        Route::get('/dashboard', function () { return redirect('/admin');});

        //Search for member
        Route::post('/search/member/', 'Admin\SearchController@getMember');
        //Documents
        Route::resource('/documents', 'Admin\Docs\IndexController');
        //Committees
        Route::resource('/committees', 'Admin\Committees\IndexController');
        Route::resource('/committees/member', 'Admin\Committees\MembersController');
        //Ministries
        Route::resource('/ministries', 'Admin\Ministries\IndexController');
        Route::resource('/ministries/member', 'Admin\Ministries\MembersController', ['except' =>['index', 'show']]);
        Route::resource('/ministries/liaison', 'Admin\Ministries\LiaisonsController', ['except' =>['index', 'show']]);
        //Empowerment
        Route::resource('groups/{id}/member', 'Admin\Empowerment\MembersController', ['except' =>['index', 'show', 'edit']]);
        Route::resource('groups', 'Admin\Empowerment\GroupsController');

        //Videos
        Route::resource('/videos', 'Admin\Video\IndexController');
        //Events
        Route::group(['prefix' => 'events'], function () {
            Route::resource('/meta/location', 'Admin\Events\LocationController', ['except' => ['index', 'show']]);
            Route::resource('/meta', 'Admin\Events\MetaController', ['except' => ['show']]);
            Route::resource('/members', 'Admin\Events\MembersController', ['only' => ['create', 'store', 'destroy']]);
            Route::resource('/price', 'Admin\Events\PriceController', ['except' => ['index', 'show']]);
            Route::resource('/picture', 'Admin\Events\PictureController', ['only' =>['create', 'store', 'destroy']]);
        });
        Route::resource('/events', 'Admin\Events\IndexController');
        //News
        Route::resource('/news/picture', 'Admin\News\PictureController', ['only' =>['create', 'store', 'destroy']]);
        Route::resource('/news', 'Admin\News\IndexController');
        //Sermons
        Route::resource('/sermons', 'Admin\Sermons\IndexController');
        Route::group(['prefix' => 'sermons'], function () {
            Route::post('/search/related', 'Admin\Sermons\SearchController@related');

app/Committee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
//use Illuminate\Database\Eloquent\SoftDeletes;

class Committee extends Model
{
    //use SoftDeletes;
    //protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'picture_id', 'slug', 'deleted_at'
    ];

    /**
     * Members that belong to the committee.
     */
    public function members()
    {
        return $this->belongsToMany('App\Member', 'committee_members')->withPivot('id', 'term_started', 'term_ended');
    }

    // Accessors -------------------------------------------------------------------------------------------------------
    public function getActiveMembersAttribute()
    {
        return $this->members()->where('term_ended', null)->get();
    }

    public function getIconClassAttribute()
    {
        $icons = [
            'missions-committee' => 'c-icon-29',
            'blue-dot-sunday-committee' => 'c-icon-6',
            'fellowship-committee' => 'c-icon-2',
            'communications-committee' => 'c-icon-47',
            'stewardship-committee' => 'c-icon-1',
            'altar-guild-committee' => 'c-icon-12',
            'communion-committee' => 'c-icon-10',
            'ushergreeter-committee' => 'c-icon-49',
            'sound-booth-committee' => 'c-icon-34',
            'office-assistance-committee' => 'c-icon-24',
            'library-committee' => 'c-icon-39',
            'road-clean-up-committee' => 'c-icon-4',
            'church-signs-committee' => 'c-icon-43',
            'website-committee' => 'c-icon-18'
        ];

        return $icons[$this->slug];
    }

    public function getTotalActiveMembersAttribute()
    {
       return count($this->members()->where('term_ended', null)->get());
    }

    public function getPastMembersAttribute()
    {
        return $this->members()->where('term_ended', '!=' , null)->get();
    }

    // Mutators -------------------------------------------------------------------------------------------------------
    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = str_slug($value, '-').'-'.'committee';
    }
}

app/Http/Controllers/Admin/Committees/IndexController.php
<?php

namespace App\Http\Controllers\Admin\Committees;

use App\Committee;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $committees = Committee::orderBy('id')->paginate(12);
        $i = $committees->firstItem();
        session()->put('pageId', $committees->currentPage());
        return view('admin.committees.index', compact('committees', 'i'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.committees.create', compact('committees'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $request['slug'] = $request->name;
        $committee = Committee::create($request->all());

        return redirect("/admin/committees/$committee->id")->with('message_success', "$committee->name committee has been added successfully!");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $committee = Committee::find($id);
        $i = 1;
        $ii = $i;
        $pageId = session()->get('pageId');

        return view('admin.committees.show', compact('committee', 'i', 'pageId', 'ii'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $committee = Committee::find($id);
        return view('admin.committees.edit', compact('committee'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required'
        ]);

        $committee = Committee::find($id);
            $committee->update($request->all());

        return redirect("/admin/committees/$committee->id")->with('message_success', "$committee->name committee has been updated successfully!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $committee = Committee::find($id);
            $name = $committee->name;
        $committee->delete();

        return redirect("/admin/committees")->with('message_info', "$name committee has been deleted.");
    }
}

app/Http/Controllers/Master/Committees/IndexController.php
<?php

namespace App\Http\Controllers\Master\Committees;

use App\Committee;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class IndexController extends Controller
{
    public function index()
    {
        $committees = Committee::orderBy('name')->get();
        $i = 1;
        return view('master.about.committees.index', compact('committees', 'i'));
    }

    public function show($slug)
    {
        $committee = Committee::where('slug', $slug)->first();
        $i = 1;
        return view('master.about.committees.show', compact('committee', 'i'));
    }
}

resources/views/admin/committees/create.blade.php
@extends('layouts.admin')

@section('title')
    Add new committee
@endsection

@section('hTitle')
    Add new committee
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    {!! Form::open(['url' => '/admin/committees', 'id' => 'myForm']) !!}
                    @include('admin.committees.formBody')
                    @include('admin.parts.btnSubmitCancel', ['btnName' => 'Save', 'cancelUrl' => '/admin/committees'])
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#myForm').on('submit', function(){
                $('#submitBtn').addClass('disabled').children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/admin/committees/edit.blade.php
@extends('layouts.admin')

@section('title')
   Edit committee
@endsection

@section('hTitle')
    Edit {{ $committee->name }} committee
@endsection

@section('breadcrumbs')
    <li><a href="{{ url('/admin/committees') }}"><i class="fa fa-table"></i> Committees</a></li>
    <li><a href="{{ url("/admin/committees/$committee->id") }}"><i class="fa fa-table"></i> {{ $committee->name }}</a></li>
    <li class="active">Edit</li>
@endsection

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">{{ $committee->name }}</div>
        <!-- /.box-header -->
        <div class="box-body">
            {!! Form::model($committee, ['method' => 'PATCH', 'action' => ['Admin\Committees\IndexController@update', $committee->id], 'id' => 'myForm']) !!}
            @include('admin.committees.formBody')
            @include('admin.parts.btnSubmitCancel', ['btnName' => 'Save', 'cancelUrl' => url("/admin/committees/$committee->id")])
            {!! Form::close() !!}
        </div>
        <!-- /.box-body -->
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $('#myForm').on('submit', function(){
                $('#submitBtn').addClass('disabled').children("i.fa").replaceWith('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
            });
        });
    </script>
@endsection

resources/views/admin/committees/formBody.blade.php
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {!! Form::label('name', 'Committee Name') !!} <i class="fa fa-asterisk text-danger" aria-hidden="true" data-toggle="tooltip" data-placement="right" title="required field"></i>
            <div class="input-group input-group-lg">
                <span class="input-group-addon" data-toggle="tooltip" data-placement="left" title="specify name"><i class="fa fa-info fa-fw" aria-hidden="true"></i></span>
                {!! Form::text('name', null, ['class' => 'form-control input-lg', 'placeholder' => 'committee name', 'autocomplete' => 'off', 'autofocus']) !!}
            </div>
            @if ($errors->has('name'))<span class="help-block"><strong>{{ $errors->first('name') }}</strong></span>@endif
        </div>
        @include('admin.parts.textarea', ['name' => 'description', 'title' => 'Committee Description'])
    </div>
</div>

resources/views/admin/committees/index.blade.php
@extends('layouts.admin')

@section('title')
    Committees
@endsection

@section('hTitle')
    Church Committees
@endsection

@section('breadcrumbs')
    <li class="active">Committees</li>
@endsection

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            Total committees <span class="badge">{{ $committees->total() }}</span>
            <a href="{{ url('/admin/committees/create') }}" class="btn btn-primary btn-xs aBtn pull-right" data-toggle="tooltip" data-placement="top" title="add new committee">
                <i class="fa fa-fw fa-plus-circle" aria-hidden="true"></i> Add
            </a>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            @include('admin.parts.message')
            <table class="table table-condensed table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Committee name</th>
                    <th class="text-center">Total Members</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($committees as $committee)
                    <tr>
                        <th scope="col">{{ $i++ }}</th>
                        <td><a class="btn btn-link btn-xs aBtn" href="{{ url("/admin/committees/$committee->id") }}"><i class="fa fa-fw fa-eye" aria-hidden="true"></i> {{ $committee->name }}</a></td>
                        <td class="text-center">{{ $committee->total_active_members }}</td>
                        <td class="text-center">
                            <a class="btn btn-default btn-xs aBtn" href="{{ url("/admin/committees/$committee->id") }}" data-toggle="tooltip" data-placement="left" title="view details">
                                <i class="fa fa-fw fa-eye" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td class="text-right">
                            @include('admin.parts.deleteBtn', ['action' => ['Admin\Committees\IndexController@destroy', $committee->id], 'class' => 'btn-xs', 'btnTitle' => "Delete $committee->name"])
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            {{ $committees->links('vendor.pagination.admin-lte') }}
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $('[data-toggle=confirmation]').confirmation({
                rootSelector: '[data-toggle=confirmation]'
            });
        });
    </script>
@endsection

resources/views/admin/committees/show.blade.php
@extends('layouts.admin')

@section('title')
    {{ $committee->name }}
@endsection

@section('hTitle')
    @include('admin.parts.btnBack', ['url' => url("/admin/committees?page=$pageId"), 'title' => 'committees list'])
    Committee: {{ $committee->name or '- title -' }}
@endsection

@section('breadcrumbs')
    <li><a href="{{ url('/admin/committees') }}"><i class="fa fa-table"></i> Committees</a></li>
    <li class="active">{{ $committee->name }}</li>
@endsection

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">{{ $committee->name }}</h3>
            <a href="{{ url("/admin/committees/$committee->id/edit") }}" class="btn btn-primary btn-xs aBtn pull-right" data-toggle="tooltip" data-placement="top" title="edit committee">
                <i class="fa fa-fw fa-pencil" aria-hidden="true"></i> edit
            </a>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @include('admin.parts.message')
            <div class="row">
                <div class="col-lg-6">
                    <h3>Description</h3>
                    <p class="lead">
                        {!! $committee->description !!}
                    </p>
                </div>
                <div class="col-lg-6">
                    <h3>
                        Active Committee members <span class="badge">{{ $committee->total_active_members }}</span>
                        <a class="btn btn-primary btn-xs aBtn" href="{{ url("/admin/committees/member/create?id=$committee->id") }}" data-container="body" data-toggle="tooltip" data-placement="top" title="add member">
                            <i class="fa fa-fw fa-plus-circle" aria-hidden="true"></i>
                        </a>
                    </h3>
                    <table class="table">
                        <tbody>
                        @foreach($committee->active_members as $member)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $member->first_name }} {{ $member->last_name }}</td>
                                <td><small>member since</small> {{ date("F j, Y", strtotime($member->pivot->term_started)) }}</td>
                                <td>
                                    <a class="btn btn-primary btn-xs aBtn" href="{{ url('/admin/committees/member/'.$member->pivot->id.'/edit') }}">
                                        <i class="fa fa-fw fa-pencil" aria-hidden="true"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <h3>Past Committee members</h3>
                    <table class="table">
                        <tbody>
                        @foreach($committee->past_members as $member)
                            <tr>
                                <td>{{ $ii++ }}</td>
                                <td>{{ $member->first_name }} {{ $member->last_name }}</td>
                                <td>{{ date("F j, Y", strtotime($member->pivot->term_started)) }}</td>
                                <td>{{ date("F j, Y", strtotime($member->pivot->term_ended)) }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            @include("admin.parts.deleteBtn", ['action' => ['Admin\Committees\IndexController@destroy', $committee->id], 'class' => 'pull-right', 'btnTitle' => "$committee->name committee"])
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $('[data-toggle=confirmation]').confirmation({
                rootSelector: '[data-toggle=confirmation]'
            });
        });
    </script>
@endsection